import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import { Navbarlogo } from "@/components/navbar/navbar.logo";

import FooterDemo from "@/components/Footer/footer"
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Hacfy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Google Analytics Script */}
         <Script
        strategy="afterInteractive"
        src={`https://www.googletagmanager.com/gtag/js?id=G-PE1HH1GCZZ`}
      />
      <Script
        id="google-analytics"
        strategy="afterInteractive"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-PE1HH1GCZZ');
          `
        }}
      />

      </head>
      <body
        className={` ${poppins.variable} antialiased bg-primary scroll-smooth`}
      >
       <div className="flex flex-col min-h-screen">
      <Navbarlogo/>
      <main className="flex-1 overflow-y-auto">
    
        
        {children}
        </main>
        </div>
        <FooterDemo />
      </body>
    </html>
  );
}